# ========================
# Cloud Build Configuration for Smart Store Backend
# ========================

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
        '.'
      ]
    dir: 'smart_store_backend'

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      ]

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
        '--region', '${_REGION}',
        '--service-account', 'smart-store-sa@${PROJECT_ID}.iam.gserviceaccount.com',
        '--allow-unauthenticated',
        '--set-env-vars',
        'GCP_PROJECT_ID=${PROJECT_ID},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},GCP_REGION=${_REGION},BIGQUERY_DATASET=mystore_analytics,FIRESTORE_COLLECTION_PRODUCTS=products,VERTEX_MODEL_SECRET_NAME=${_VERTEX_MODEL_SECRET_NAME},VERTEX_MODEL_ID_VALUE=gemini-2.5-flash-preview-09-2025,PUBSUB_TOPIC_ID=${_PUBSUB_TOPIC_ID},LOG_LEVEL=INFO'
      ]

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

substitutions:
  _SERVICE_NAME: 'smart-store-backend'
  _REPO_NAME: 'smart-store-repo'
  _REGION: 'europe-west3'
  _GCS_BUCKET_NAME: 'mystore-476317-bucket'
  _VERTEX_MODEL_SECRET_NAME: 'vertex-model-id'
  _PUBSUB_TOPIC_ID: 'xlsx-processing-topic'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  substitution_option: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'

timeout: 1800s
